### ISSUE TITLE
[2주 차 과제] 아이폰 기본 날씨 APP 구현

### ISSUE THREAD

**Issue by yeonsu0-0** [DO-SOPT-iOS-Part/KimYeonsu-assignment#1]
## 🌥️ Weather App
<img width="600" alt="image" src="https://github.com/DO-SOPT-iOS-Part/KimYeonsu-assignment/assets/107970815/52a1a1fd-d1bd-43f7-8cbf-d50d3eda61fc">

## TODO

- [ ] 나의 위치 뷰 터치 시 상세보기 뷰로 화면 전환(push)
- [ ] 상세보기 뷰 스크롤 구현
- [ ] 리스트 보기 터치 시 화면 전환(pop)
